# deps stage
FROM node:16-alpine3.11 as deps
WORKDIR /usr/src/deps

COPY package.json .
COPY yarn.lock .
COPY .npmrc .

RUN yarn


# build stage
FROM node:16-alpine3.11 as build
WORKDIR /usr/src/build
ENV NODE_ENV production


COPY --from=deps /usr/src/deps/ .
RUN ls node_modules | wc -l
COPY . .

RUN yarn build


# server
FROM node:16-alpine3.11 as app
WORKDIR /usr/src/app
ENV NODE_ENV production
USER node

COPY --from=build --chown=node:node /usr/src/build .

CMD ["yarn", "start"]
